export const EventData = [
  {
    id: 1,
    title: "The Science Show",
    address: "Luyi",
    category: "Engineering",
    tags: ["Science","Horror", "Sci-fi"],
    isVirtual: true,
  },
  {
    id: 2,
    title: "Structural Engineer",
    address: "Budapest",
    category: "Granite Surfaces",
    tags:  ["Science","Horror"],
    isVirtual: true,
  },
  {
    id: 3,
    title: "Budget/Accounting Analyst III",
    address: "Kayes",
    category: "Construction Clean and Final Clean",
    tags:["Science","Horror","Reduntant"],
    isVirtual: true,
  },
  {
    id: 4,
    title: "Software Test Engineer III",
    address: "Baturité",
    category: "Wall Protection",
    tags: ["Green"],
    isVirtual: true,
  },
  {
    id: 5,
    title: "Technical Writer",
    address: "Fubei",
    category: "Temp Fencing, Decorative Fencing and Gates",
    tags: ["Purple"],
    isVirtual: true,
  },
  {
    id: 6,
    title: "Office Assistant II",
    address: "Frydek",
    category: "Electrical",
    tags: ["Aquamarine"],
    isVirtual: false,
  },
  {
    id: 7,
    title: "Research Associate",
    address: "Potosí",
    category: "Drywall & Acoustical (MOB)",
    tags: ["Maroon"],
    isVirtual: false,
  },
  {
    id: 8,
    title: "Staff Scientist",
    address: "Staroderevyankovskaya",
    category: "Masonry",
    tags: ["Puce"],
    isVirtual: false,
  },
  {
    id: 9,
    title: "Accountant II",
    address: "Zhouling",
    category: "Landscaping & Irrigation",
    tags: ["Puce"],
    isVirtual: true,
  },
  {
    id: 10,
    title: "Recruiting Manager",
    address: "Chuchkovo",
    category: "Waterproofing & Caulking",
    tags: ["Indigo"],
    isVirtual: false,
  },
  {
    id: 11,
    title: "Data Coordiator",
    address: "Trollhättan",
    category: "RF Shielding",
    tags: ["Pink"],
    isVirtual: true,
  },
  {
    id: 12,
    title: "Nurse Practicioner",
    address: "Linqu",
    category: "Electrical",
    tags: ["Aquamarine"],
    isVirtual: false,
  },
  {
    id: 13,
    title: "Internal Auditor",
    address: "Hiratachō",
    category: "Glass & Glazing",
    tags: ["Yellow"],
    isVirtual: false,
  },
  {
    id: 14,
    title: "Senior Quality Engineer",
    address: "Hankasalmi",
    category: "HVAC",
    tags: ["Purple"],
    isVirtual: false,
  },
  {
    id: 15,
    title: "Software Engineer IV",
    address: "Poncokusumo",
    category: "Roofing (Asphalt)",
    tags: ["Teal"],
    isVirtual: false,
  },
  {
    id: 16,
    title: "Marketing Manager",
    address: "Pulau Pinang",
    category: "Electrical and Fire Alarm",
    tags: ["Blue"],
    isVirtual: false,
  },
  {
    id: 17,
    title: "Social Worker",
    address: "Houbai",
    category: "Termite Control",
    tags: ["Violet"],
    isVirtual: true,
  },
  {
    id: 18,
    title: "Nuclear Power Engineer",
    address: "Ar Ruways",
    category: "Curb & Gutter",
    tags: ["Indigo"],
    isVirtual: false,
  },
  {
    id: 19,
    title: "Community Outreach Specialist",
    address: "Carmen de Viboral",
    category: "Exterior Signage",
    tags: ["Green"],
    isVirtual: true,
  },
  {
    id: 20,
    title: "Technical Writer",
    address: "Blarney",
    category: "Asphalt Paving",
    tags: ["Puce"],
    isVirtual: false,
  }
];